name: build rt-k3-G-code(NewWay)


on: 
  workflow_dispatch:
    inputs:
      eth0:
        description: 'Your Eth0 Mac'
        required: true
        default: '00:11:22:33:44:55'
      Wlan0:
        description: 'Your Eth1(2.4g) Mac'
        required: true
        default: '00:11:22:33:44:66'
      Wlan1:
        description: 'Your Eth2(5g) Mac'
        required: true
        default: '00:11:22:33:44:77'
  
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ET0MACADDR: github.event.inputs.eth0     
  MACADDR1_24G: github.event.inputs.Wlan0
  MACADDR2_5G: github.event.inputs.Wlan1
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: Show Arg Max
      run: getconf ARG_MAX
    
    - name: Clone source code
      run: |       
        #git clone https://github.com/RMerl/asuswrt-merlin
        sudo apt install automake-1.15
        mkdir -p "$HOME/amcfwm" && wget -q "https://raw.githubusercontent.com/Adamm00/am_cfwm/master/amcfwm.sh" -O "$HOME/amcfwm/amcfwm.sh" && chmod 755 "$HOME/amcfwm/amcfwm.sh"
        sh $HOME/amcfwm/amcfwm.sh repo
        #git clone https://github.com/godcong/asuswrt-merlin.ng
        git clone https://github.com/ghostnup/asuswrt-merlin.ng
        git clone https://github.com/ghostnup/k3screenctrl asuswrt-merlin.ng/release/src/router/k3screenctrl 
        git clone https://github.com/ghostnup/am-toolchains.git
        #sh $HOME/amcfwm/amcfwm.sh install
        sudo mkdir -p /media/asuswrt/
        sudo mkdir -p /opt/images/
                
        #echo "print dir k3screenctrl"
        #ls -A asuswrt-merlin.ng/release/src/router
        
        #echo "print dir brcm-arm"
        #ls -A asuswrt-merlin/release/src-rt-6.x.4708/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin
        
    #- name: Modify File
      #run: |  
     
        #cd  /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed
        #echo "replace mac address from $(cat rt-k3_nvram.txt | grep ^et0macaddr) to ${{ env.ET0MACADDR }}"
        #sed -i 's/^\(et0macaddr=\).*/\1${{ env.ET0MACADDR }}/g' rt-k3_nvram.txt
        #echo "replace mac 2.4g address from $(cat rt-k3_nvram.txt | grep ^1:macaddr) to ${{ env.MACADDR1_24G }}"
        #sed -i 's/^\(1:macaddr=\).*/\1${{ env.MACADDR1_24G }}/g' rt-k3_nvram.txt
        #echo "replace mac 5g address from $(cat rt-k3_nvram.txt | grep ^2:macaddr) to ${{ env.MACADDR2_5G }}"
        #sed -i 's/^\(2:macaddr=\).*/\1${{ env.MACADDR2_5G }}/g' rt-k3_nvram.txt
    - name: Build Firmware
      run: |
        #export PATH=$PATH:/opt/brcm/hndtools-mipsel-linux/bin:/opt/brcm/hndtools-mipsel-uclibc/bin:
        export PATH=$PATH:/opt/brcm-arm/bin
        

        cd /asuswrt-merlin.ng/release/src-rt
        echo "add tag to version"
        sed -i 's/EXTENDNO=.*/&_${{ env.MERLIN_TAG }}/g' version.conf
    
        cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/
        #cd /asuswrt-merlin.ng/release
        echo $(pwd)
        cd src
        make rt-k3
        echo "build image done"     
        
        #cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/
        cd src
        cd cfe
        make
        echo "build cfe done"
        
#    - name : Upload packages
#      uses: actions/upload-artifact@master
#      if: always()
#      with:
#        name: Padavan-packages
#        path: /opt/images
    - name: Move file && Checksum
      run: |
        sudo mv -f /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/image/*.trx /opt/images/
        sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed/rt-k3_nvram.txt /opt/images/
        sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/cfe*.bin /opt/images/
        #sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt/version.conf /opt/images/
        
        sha256sum /opt/images/* > /opt/images/checksum.txt
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        files: "/opt/images/*.*"  
        tag_name: ${{ env.BUILD_DATE }}_mainline_k3_${{ env.MERLIN_TAG }}
        body: |
          this is only a latest build from mainline
          version: https://github.com/godcong/asuswrt-merlin.ng/commit/${{ env.MERLIN_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
